Initial version of an extracted parser library
matter-labs/yul-syntax-tools pull request #1
Opened 2024-08-19 18:07 UTC by sayon

2024-08-19 18:10 UTC, sayon commented
@antonbaliasnikov please take a look. This code was extracted from the compiler, but I would like to check with you
- how to properly set up CI here
- whether all tests are in tact (and none is lost)
- how to integrate the CI here with CI in other repos

2024-08-20 08:30 UTC, antonbaliasnikov commented
> @antonbaliasnikov please take a look. This code was extracted from the compiler, but I would like to check with you
> 
> * how to properly set up CI here
> * whether all tests are in tact (and none is lost)
> * how to integrate the CI here with CI in other repos

@sayon , it requires an additional task to set up CI for this repo.

In the meantime, I have the following questions:
1. You copied `cli-tests` in this repository - why? I don't think they are required here.
2. When you say "tests are intact" - what exactly do you mean? I don't think we can do more than running `cargo test` and check that everything is passing. Do you have something more in mind?
3. About CI integration - what exactly do you mean? For example, we have a ticket [CPR-1560](https://linear.app/matterlabs/issue/CPR-1560/find-a-solution-for-testing-dependencies-on-the-whole-system) about testing dependencies, but it's not a common thing.

2024-08-20 08:33 UTC, antonbaliasnikov commented
Also, this `TruffleHog` expected check must be disabled in the way it is enabled today:
<img width="844" alt="image" src="https://github.com/user-attachments/assets/60593c08-5fdc-4437-9d09-2187978804ac">

It expects _the job_ to exist, but we provide _check_ like that.

@sayon are you an admin of this repo by any occasion? If not, we'll have to ask admins to disable it later.

2024-08-20 11:31 UTC, sayon commented
> Also, this `TruffleHog` expected check must be disabled in the way it is enabled today: <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/22070213/359400340-60593c08-5fdc-4437-9d09-2187978804ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTM2NzYsIm5iZiI6MTcyNDE1MzM3NiwicGF0aCI6Ii8yMjA3MDIxMy8zNTk0MDAzNDAtNjA1OTNjMDgtNWZkYy00NDM3LTlkMDktMjE4Nzk3ODgwNGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDExMjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExY2M1N2FlZGMxODMyMDVhYWNlZjAzZDAzNzViM2M0MGJkNWE5NWVlMTYzMDkyOTQwY2MxNzQ2NzhhMDk0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SHElnz2drWotUpP_95dQimXFmh5zMcUtQPBhi9NRP4k">
> 
> It expects _the job_ to exist, but we provide _check_ like that.
> 
> @sayon are you an admin of this repo by any occasion? If not, we'll have to ask admins to disable it later.

No I am not the admin, this can be disabled later by Oleksandr. I realized it would be better to discuss other points on a call.

2024-08-22 10:31 UTC, hedgar2017 commented
@sayon I'm not an admin either. We're not admins of newly created repos anymore.

2024-08-22 10:33 UTC, hedgar2017 requested changes
We did not need this repo.
You can convert the original repo into a workspace a simply have this library as a second crate there.

2024-08-22 10:35 UTC, hedgar2017 requested changes

2024-08-22 10:35 UTC, hedgar2017 commented on src/message_type.rs
> +//! The compiler message type.
I believe this module is unused.
Does `cargo` complain about it?

2025-01-20 15:27 UTC, closed without merging